config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'main#index'

  # Orders
  resources :orders
  get 'orders/:id/complete', to: 'orders#complete'

  # Stands
  resources :stands

  # Places
  resources :places

  # Users
  resources :users

  # Teams
  resources :teams

  # Challenges
  resources :challenges
end

app/models/order.rb
class Order < ApplicationRecord
  validates :place, presence: true
  validates :place_details, length: { maximum: 150 }
  validates :content, presence: true, length: { minimum: 5, maximum: 500 }
  validates :author, presence: true, length: { minimum: 2, maximum: 150 }
  validates :recontact_info, length: { maximum: 150 }

  enum status: [ :active, :archived, :completed ]

  belongs_to :place, {optional: true}
  belongs_to :stand, {optional: true}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include ApplicationHelper

  authorize_resource

  def index
    if params.has_key?(:stand_id)
      @stand = Stand.find(params[:stand_id])
      @orders = Order.where('stand_id' => params[:stand_id], 'status' => :active)
    elsif params.has_key?(:status)
      @orders = Order.where('status' => params[:status])
    else
      @statuses = Order.statuses
      @stands = Stand.all
      @orders = Order.where('status' => :active)
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    if !user_signed_in? and !allos_dates
      redirect_to root_path
    end

    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if !@order.place.nil?  && !@order.place.stand.nil?
      @order.stand = @order.place.stand
    end

    if (user_signed_in? or verify_recaptcha(model: @user)) && @order.save
      Telegram.bot.send_message chat_id: -219439105, text: telegram_message, parse_mode: :Markdown
      redirect_to orders_path
    else
      @places = Place.all
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @stands = Stand.all
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to orders_path
    else
      render 'edit'
    end
  end

  def complete
    @order = Order.find(params[:id])
    @order.status = :completed
    @order.save

    if params[:stand_id] != nil
      url = orders_path + '?stand_id=' + params[:stand_id]
    else
      url = orders_path
    end

    redirect_to url
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:content, :author, :stand_id, :place_id, :status, :recontact_info, :place_details)
  end

  def telegram_message
    if !@order.place.nil?  && !@order.place.stand.nil?
      r = '*Commande #' + @order.id.to_i.to_s + ' attribuée à ' + @order.stand.label + "*\n"
    else
      r = '*Commande #' + @order.id.to_i.to_s + "*\n"
    end
    r += '*Demandeur : *' + @order.author + "\n"
    if @order.recontact_info != ''
      r += '_Contact info : _' + @order.recontact_info + "\n"
    end
    r += '*Lieu : *' + @order.place.label + "\n"
    if @order.place_details != ''
      r += '_Détails du lieu : _' + @order.place_details + "\n"
    end
    r += "\n*Contenu de la commande : *" + @order.content + "\n"

    r
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="page-header">
  <h1>Éditer la commande <small>#<%= @order.id %></small></h1>
</div>


<%= simple_form_for @order, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
    <%= f.association :place %>
    <%= f.input :place_details %>
    <%= f.association :stand %>
    <%= f.input :content %>
    <%= f.input :author %>
    <%= f.input :recontact_info %>
    <%= f.input :status %>

    <%= f.button :submit %>
<% end %>

app/views/orders/index.html.erb
<div class="page-header">
  <h1>
    Liste des commandes
    <small>
      <% if @stand %>
          <%= @stand.label %>
      <% end %>
    </small>
  </h1>
</div>

<% if @stands %>
    Filtrer par stand :
    <% @stands.each do |stand| %>
        <a href="<%= orders_path %>?stand_id=<%= stand.id %>">
          <%= stand.label %>
        </a>
        <% if stand != @stands.last %>
            -
        <% end %>
    <% end %><br>
    Filtrer par statut :
    <% @statuses.each do |label, id| %>
        <a href="<%= orders_path %>?status=<%= id %>">
          <%= label %>
        </a>
    <% end %>
    <hr>
<% end %>

<table class="table table-hover datatable">
  <thead>
    <tr>
      <th>#</th>
      <th>Lieu</th>
      <th>Description</th>
      <th>Demandeur</th>
      <th>Affectation</th>
      <th>Heure de commande</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.place ? order.place.label : '' %></td>
      <td><%= order.content %></td>
      <td><%= order.author %></td>
      <td><%= order.stand ? order.stand.label : '' %></td>
      <td><%= order.created_at.to_formatted_s(:short) %></td>
      <td>
        <div class="btn-group btn-group-xs">
          <a href="<%= order_path(order) %>" class="btn btn-primary">
            <i class="fa fa-eye"></i>
          </a>
          <a href="<%= edit_order_path(order) %>" class="btn btn-warning">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<%= orders_path %>/<%= order.id %>/complete<%= @stand ? '?stand_id=' + @stand.id.to_i.to_s : ''%>" class="btn btn-success">
            <i class="fa fa-check"></i>
          </a>
          <a href="<%= order_path(order) %>" data-method="delete" data-confirm="Êtes-vous sur ?"
             class="btn btn-danger">
            <i class="fa fa-trash"></i>
          </a>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= javascript_include_tag params[:controller] %>

app/views/orders/new.html.erb
<div class="page-header">
  <img class="img-responsive" src="/crepe.jpg" alt="">
  <h1>Passe ta commande !</h1>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <h3><i class="fa fa-phone"></i> Tes listeux te proposent</h3>
    <ol>
      <li>Crêpes</li>
      <li>Massage</li>
      <li>Blagues</li>
      <li>Twerk</li>
      <li>Câlin</li>
      <li>Histoire</li>
      <li>Fast food</li>
      <li>Compliment</li>
      <li title="Commande ta place">Place</li>
    </ol>
  </div>
  <div class="col-xs-12 col-sm-8">
    <%= simple_form_for @order do |f| %>
        <%= f.association :place %>
        <%= f.input :place_details, :input_html => {:maxlength => 150} %>
        <%= f.input :content, :input_html => {:maxlength => 500} %>
        <%= f.input :author, :input_html => {:maxlength => 150} %>
        <%= f.input :recontact_info, :input_html => {:maxlength => 150} %>

        <% if !user_signed_in?  %>
            <%= recaptcha_tags %>
        <% end %>

        <%= f.button :submit, class: "pull-right" %>
    <% end %>
  </div>

</div>

app/views/orders/show.html.erb
<div class="page-header">
  <h1>Commande <small>#<%= @order.id %></small></h1>
</div>

<a href="<%= edit_order_path(@order) %>">Éditer</a>

<p>
  <em>Auteur : </em>
  <%= @order.author %>
  <br>
  <em>Information contact :</em>
  <%= @order.recontact_info %>
  <br>
  <em>Lieu :</em>
  <%= @order.place ? @order.place.label : '' %>
  <br>
  <em>Détails du lieu :</em>
  <%= @order.place_details %>
  <br>
  <em>Passée le :</em>
  <%= l @order.created_at, format: :short %>
</p>

<% if @order.stand %>
    <p>
      <em>Affectation : </em>
      <%= @order.stand.label %>
    </p>
<% end %>

<p>
  <strong>Description : </strong>
  <%= @order.content %>
</p>