config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'main#index'

  # Orders
  resources :orders
  get 'orders/:id/complete', to: 'orders#complete'

  # Stands
  resources :stands

  # Places
  resources :places

  # Users
  resources :users

  # Teams
  resources :teams

  # Challenges
  resources :challenges
end

app/models/stand.rb
class Stand < ApplicationRecord
  validates :label, presence: true
  validates :location, presence: true

  has_many :order, dependent: :nullify
  has_many :place, dependent: :nullify

  def name
    label
  end
end

app/controllers/stands_controller.rb
class StandsController < ApplicationController

  authorize_resource

  def index
    @stands = Stand.all
  end

  def new
    @stand = Stand.new
  end

  def create
    @stand = Stand.new(stand_params)
    if @stand.save
      redirect_to stands_path
    else
      render 'new'
    end
  end

  def destroy
    @stand = Stand.find(params[:id])
    @stand.destroy

    redirect_to stands_path
  end

  private

  def stand_params
    params.require(:stand).permit(:label, :location)
  end
end

app/helpers/stands_helper.rb
module StandsHelper
end

app/views/stands/index.html.erb
<div class="page-header">
  <h1>Les stands</h1>
</div>

<a href="<%= new_stand_path %>" class="btn btn-default pull-right">
  <i class="fa fa-plus"></i> Nouveau
</a>


<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nom</th>
      <th>Position</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stands.each do |stand| %>
    <tr>
      <td><%= stand.id %></td>
      <td><%= stand.label %></td>
      <td><%= stand.location %></td>
      <td>
        <div class="btn-group btn-group-sm">
          <a href="<%= stand_path(stand) %>" data-method="delete"
             data-confirm="Êtes-vous sur ? Cela désaffectera toutes les commandes associées à ce stand."
             class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stands/new.html.erb
<div class="page-header">
  <h1>Nouveau stand</h1>
</div>

<%= simple_form_for @stand, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, url: stands_path do |f| %>
    <%= f.input :label %>
    <%= f.input :location %>

    <%= f.button :submit %>
<% end %>