config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'main#index'

  # Orders
  resources :orders
  get 'orders/:id/complete', to: 'orders#complete'

  # Stands
  resources :stands

  # Places
  resources :places

  # Users
  resources :users

  # Teams
  resources :teams

  # Challenges
  resources :challenges
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="center">
<a href="/charte.pdf">Charte de conduite</a>
    <br>
    Retrouvez nous sur les réseaux sociaux</p>
  <%= render 'layouts/social' %>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-93088247-1', 'auto');
      ga('send', 'pageview');

  </script>
</footer>

app/views/layouts/_header.html.erb
<!-- Navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" aria-expanded="false" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="fa fa-bars"></span>
        </button>
        <a href="<%= root_path %>" class="navbar-brand"><img src="/home.png" id="home" alt=""></a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if controller.controller_name == "main" %>
            <li class=""><a href="#membres">Membres</a></li>
            <li class=""><a href="#voyages">Voyages</a></li>
            <li class=""><a href="#partners">Partenaires</a></li>
          <% else %>
          <li class=""><a href="/#membres">Membres</a></li>
          <li class=""><a href="/#voyages">Voyages</a></li>
          <li class=""><a href="/#partners">Partenaires</a></li>
          <% end %>

          <% if allos_dates %>
            <%= nav_link 'Passe ta commande !', new_order_path %>
          <% end %>
          <%= nav_link 'Défie-nous', challenges_path %>
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bonjour <%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <%= nav_link 'Défis', challenges_path %>
                  <%= nav_link 'Commandes', orders_path %>
                  <%= nav_link 'Stands', stands_path %>
                  <%= nav_link 'Lieux', places_path %>
                  <%= nav_link 'Utilisateurs', users_path %>
                  <%= nav_link 'Pôles', teams_path %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
          <% end %>
        </ul>
      </div>
  </div>
</nav>

<% if notice %>
    <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_social.html.erb
<h3 class="social">
   <a href="//snapchat.com/add/savage-officiel" class="fa fa-snapchat-square"></a>
   <a href="//facebook.com/ListeBDESavage" class="fa fa-facebook-square"></a>
   <a href="//www.instagram.com/listebdesavage/" class="fa fa-instagram"></a>
   <a href="//twitter.com/ListeBDESavage" class="fa fa-twitter-square"></a>
   <a href="//www.youtube.com/channel/UCsMqdJVWRwen-f9alOOjScg" class="fa fa-youtube-square"></a>
 </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Savage</title>
    <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container main">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Savage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>